// Generated by gencpp from file fake_exo/servResponse.msg
// DO NOT EDIT!


#ifndef FAKE_EXO_MESSAGE_SERVRESPONSE_H
#define FAKE_EXO_MESSAGE_SERVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fake_exo
{
template <class ContainerAllocator>
struct servResponse_
{
  typedef servResponse_<ContainerAllocator> Type;

  servResponse_()
    : error()  {
    }
  servResponse_(const ContainerAllocator& _alloc)
    : error(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::fake_exo::servResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fake_exo::servResponse_<ContainerAllocator> const> ConstPtr;

}; // struct servResponse_

typedef ::fake_exo::servResponse_<std::allocator<void> > servResponse;

typedef boost::shared_ptr< ::fake_exo::servResponse > servResponsePtr;
typedef boost::shared_ptr< ::fake_exo::servResponse const> servResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fake_exo::servResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fake_exo::servResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fake_exo::servResponse_<ContainerAllocator1> & lhs, const ::fake_exo::servResponse_<ContainerAllocator2> & rhs)
{
  return lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fake_exo::servResponse_<ContainerAllocator1> & lhs, const ::fake_exo::servResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fake_exo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fake_exo::servResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fake_exo::servResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fake_exo::servResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fake_exo::servResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fake_exo::servResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fake_exo::servResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fake_exo::servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eca8b96616c32aacf1be8bbf14c70eba";
  }

  static const char* value(const ::fake_exo::servResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeca8b96616c32aacULL;
  static const uint64_t static_value2 = 0xf1be8bbf14c70ebaULL;
};

template<class ContainerAllocator>
struct DataType< ::fake_exo::servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fake_exo/servResponse";
  }

  static const char* value(const ::fake_exo::servResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fake_exo::servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string error\n"
"\n"
;
  }

  static const char* value(const ::fake_exo::servResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fake_exo::servResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fake_exo::servResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fake_exo::servResponse_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FAKE_EXO_MESSAGE_SERVRESPONSE_H
