// Generated by gencpp from file fake_exo/servRequest.msg
// DO NOT EDIT!


#ifndef FAKE_EXO_MESSAGE_SERVREQUEST_H
#define FAKE_EXO_MESSAGE_SERVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fake_exo
{
template <class ContainerAllocator>
struct servRequest_
{
  typedef servRequest_<ContainerAllocator> Type;

  servRequest_()
    : code()  {
    }
  servRequest_(const ContainerAllocator& _alloc)
    : code(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::fake_exo::servRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fake_exo::servRequest_<ContainerAllocator> const> ConstPtr;

}; // struct servRequest_

typedef ::fake_exo::servRequest_<std::allocator<void> > servRequest;

typedef boost::shared_ptr< ::fake_exo::servRequest > servRequestPtr;
typedef boost::shared_ptr< ::fake_exo::servRequest const> servRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fake_exo::servRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fake_exo::servRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fake_exo::servRequest_<ContainerAllocator1> & lhs, const ::fake_exo::servRequest_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fake_exo::servRequest_<ContainerAllocator1> & lhs, const ::fake_exo::servRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fake_exo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fake_exo::servRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fake_exo::servRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fake_exo::servRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fake_exo::servRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fake_exo::servRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fake_exo::servRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fake_exo::servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d589d39a46fa5aba4838a23b9cc4e62";
  }

  static const char* value(const ::fake_exo::servRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d589d39a46fa5abULL;
  static const uint64_t static_value2 = 0xa4838a23b9cc4e62ULL;
};

template<class ContainerAllocator>
struct DataType< ::fake_exo::servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fake_exo/servRequest";
  }

  static const char* value(const ::fake_exo::servRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fake_exo::servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string code\n"
;
  }

  static const char* value(const ::fake_exo::servRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fake_exo::servRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fake_exo::servRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fake_exo::servRequest_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FAKE_EXO_MESSAGE_SERVREQUEST_H
