// Generated by gencpp from file gui_pkg/serv.msg
// DO NOT EDIT!


#ifndef GUI_PKG_MESSAGE_SERV_H
#define GUI_PKG_MESSAGE_SERV_H

#include <ros/service_traits.h>


#include <gui_pkg/servRequest.h>
#include <gui_pkg/servResponse.h>


namespace gui_pkg
{

struct serv
{

typedef servRequest Request;
typedef servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct serv
} // namespace gui_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gui_pkg::serv > {
  static const char* value()
  {
    return "62d2895a600383a28702b76d8606b327";
  }

  static const char* value(const ::gui_pkg::serv&) { return value(); }
};

template<>
struct DataType< ::gui_pkg::serv > {
  static const char* value()
  {
    return "gui_pkg/serv";
  }

  static const char* value(const ::gui_pkg::serv&) { return value(); }
};


// service_traits::MD5Sum< ::gui_pkg::servRequest> should match
// service_traits::MD5Sum< ::gui_pkg::serv >
template<>
struct MD5Sum< ::gui_pkg::servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gui_pkg::serv >::value();
  }
  static const char* value(const ::gui_pkg::servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gui_pkg::servRequest> should match
// service_traits::DataType< ::gui_pkg::serv >
template<>
struct DataType< ::gui_pkg::servRequest>
{
  static const char* value()
  {
    return DataType< ::gui_pkg::serv >::value();
  }
  static const char* value(const ::gui_pkg::servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gui_pkg::servResponse> should match
// service_traits::MD5Sum< ::gui_pkg::serv >
template<>
struct MD5Sum< ::gui_pkg::servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gui_pkg::serv >::value();
  }
  static const char* value(const ::gui_pkg::servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gui_pkg::servResponse> should match
// service_traits::DataType< ::gui_pkg::serv >
template<>
struct DataType< ::gui_pkg::servResponse>
{
  static const char* value()
  {
    return DataType< ::gui_pkg::serv >::value();
  }
  static const char* value(const ::gui_pkg::servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GUI_PKG_MESSAGE_SERV_H
